# This is a basic workflow to help you get started with Actions

name: jekyll-gh-pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install Jekyll Env
        run: |
          echo 安装 Jekyll 环境
          sudo gem install bundler jekyll
          echo gem install minima
          sudo gem install minima
          echo gem install jekyll-readme-index
          sudo gem install jekyll-readme-index
          echo gem install jekyll-feed
          sugo gem install jekyll-feed
          echo gem install jekyll-github-metadata
          sugo gem install jekyll-github-metadata
          echo gem install jekyll-readme-index
          sugo gem install jekyll-readme-index
          echo gem install jekyll-relative-links
          sugo gem install jekyll-relative-links
          echo gem install jekyll-coffeescript
          sugo gem install jekyll-coffeescript
          echo gem install jekyll-default-layout
          sugo gem install jekyll-default-layout
          echo gem install jekyll-gist
          sugo gem install jekyll-gist
          echo gem install jekyll-optional-front-matter
          sugo gem install jekyll-optional-front-matter
          echo gem install jekyll-paginate
          sugo gem install jekyll-paginate
          echo gem install jekyll-paginate-v2
          sugo gem install jekyll-paginate-v2
          echo gem install jekyll-titles-from-headings
          sugo gem install jekyll-titles-from-headings

      - name: Build Jekyll
        run: |
          echo 开始 Jekyll 构建
          bundle exec jekyll build

      - name: Deploy Github Pages
        run: |
          echo 开始 Gtihub Pages 发布
